version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: "/filiikot"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/filiikot/rootfs/opt/filiikot"
  schedule:
    interval: daily
