---
name: Filiikot
version: dev
slug: filiikot
description: A Filiikot add-on for Home Assistant
url: https://github.com/filii-lamberti/addon-filiikot
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
hassio_api: true
homeassistant_api: true
ports:
  3000/tcp: 8046 # K+O+T
options:
schema:
  logging: bool?
  debugging: bool?
image: ghcr.io/filii-lamberti/filiikot/{arch}