name: Continuous integration

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master
      - develop

jobs:
  continuous-integration:
    uses: filii-lamberti/repository/.github/workflows/ci.yml@main
    with:
      addon: filiikot
