name: Continuous integration

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches: [master]

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Use Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: ./filiikot/rootfs/opt/filiikot/package-lock.json
      - name: Install ESLint and dependencies
        run: npm install
        working-directory: ./filiikot/rootfs/opt/filiikot
      - name: Run ESLint
        run: node_modules/eslint/bin/eslint.js app.js
        working-directory: ./filiikot/rootfs/opt/filiikot

  test:
    needs: lint
    name: Test code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set add-on version
        run: |
          sed -i "s/dev/latest/g" filiikot/config.json
      - name: Build and push tagged Docker image
        uses: home-assistant/builder@2021.09.0
        with:
          args: |
            --amd64 \
            --target filiikot \
            --docker-hub "ghcr.io/${{ github.repository_owner }}"

  update_release_draft:
    name: Release Drafter
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
